"""
Django settings for dingtalk_bot project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os


def env_to_bool(env, default):
    str_val = os.environ.get(env)
    return default if str_val is None else str_val == 'True'

DINGTALK_ROBOT_CODE = os.environ.get("DINGTALK_ROBOT_CODE", None)

DINGTALK_CLIENT_ID = os.environ.get("DINGTALK_CLIENT_ID")

DINGTALK_CLIENT_SECRET= os.environ.get("DINGTALK_CLIENT_SECRET")

REDIS_ADDR = os.environ.get("REDIS_ADDR", "127.0.0.1:6379")

REDIS_DATABASE_NUM = os.environ.get("REDIS_DATABASE_NUM", "0")

REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", "")

ARGO_WORKFLOWS_DOMAIN = os.environ.get("ARGO_WORKFLOWS_DOMAIN", "https://workflows.example.com")

ARGO_WORKFLOWS_TOKEN = os.environ.get("ARGO_WORKFLOWS_TOKEN", "undefined")

ARGO_WORKFLOWS_WORKER_NAMESPACE = os.environ.get("ARGO_WORKFLOWS_WORKER_NAMESPACE", "Undefined_workflows_task_namespace")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c^u#(3ol19y*zfu+3a%o%&rr46b3l4)4x*$0h7d_c3866t2r)0'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env_to_bool("DJANGO_DEBUG", False)

ALLOWED_HOSTS = [
    "*",
    "127.0.0.1",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "daphne",
    'django.contrib.staticfiles',
    'customRobot',
    # "background_task"
    'django_q'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.gzip.GZipMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.http.ConditionalGetMiddleware',
]

ROOT_URLCONF = 'dingtalk_bot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dingtalk_bot.wsgi.application'

ASGI_APPLICATION = "dingtalk_bot.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOG_PATH = os.path.join(BASE_DIR, "logs")
if not os.path.exists(LOG_PATH):
    os.makedirs(LOG_PATH, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'root': {
        'level': 'INFO',
        'handlers': ['console'],
    },
    'formatters': {
        'verbose': {
            'format': '[%(asctime)s] %(levelname)s (%(threadName)-10s) [%(name)s.%(funcName)s:%(lineno)d %(module)s] %(message)s',
        }
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'log_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOG_PATH, 'djangoblog.log'),
            'maxBytes': 1024*1024*10,   # 日志 100M 轮转
            'backupCount': 5,
            'formatter': 'verbose',
            'delay': True,
            'encoding': 'utf-8'
        },
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'verbose'
        },
        'null': {
            'class': 'logging.NullHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'dingtalk_bot': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,  # 是否向上传递日志流
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django-q': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,  # 是否向上传递日志流
        },
    }
}

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": f"redis://:{REDIS_PASSWORD}@{REDIS_ADDR}/{REDIS_DATABASE_NUM}",
#         "OPTIONS": {
#             "REDIS_CLIENT_CLASS": "rediscluster.RedisCluster",  # 连接类
#         #     "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             "CONNECTION_POOL_CLASS": "rediscluster.connection.ClusterConnectionPool",  # 连接池类
#             "SOCKET_CONNECT_TIMEOUT": 5,
#             "SOCKET_TIMEOUT": 10,
#             "CONNECTION_POOL_KWARGS": {
#                 'skip_full_coverage_check': True,
#                 "max_connections": 10
#             },
#             "SERIALIZER": "django_redis.serializers.json.JSONSerializer",
#             'REDIS_CLIENT_KWARGS': {"decode_responses": True},
#         },
#         "KEY_PREFIX": "dingtalk_bot"  # 默认 KEY_PREFIX:VERSION:key, 暂未使用
#     }
# }

Q_CLUSTER = {
    'name': 'project',
    'workers': 4,
    # 'recycle': 500,
    'timeout': 60,
    # 'compress': True,
    # 'cpu_affinity': 1,
    # 'save_limit': 250,
    # 'queue_limit': 500,
    # 'label': 'DjangoQ',
    # "django_redis": "default"
    "redis": {
        "host": REDIS_ADDR.split(":")[0],
        "port": REDIS_ADDR.split(":")[1],
        "db": REDIS_DATABASE_NUM,
        "password": REDIS_PASSWORD
    }
}

## 设置 redis-cluster 任意节点地址
REDIS_CLUSTER_NODES = [
    {"host": REDIS_ADDR.split(":")[0], "port": REDIS_ADDR.split(":")[1]},
]